[package]
name = "library_app"
version = "0.1.0"
edition = "2024"

[dependencies]
lib_boworring ={ path = "../lib_boworring"}
inventory = { path = "../inventory" }
lib_users = { path = "../lib_users" }